name: "[CI] On push to release"

on:
  push:
    branches: [release]
    

jobs:
  inspection_and_tests:
    name: Inspection and Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install npm dependencies
      run: npm install
    - name: Run format check with prettier
      run: npm run format:check
    - name: Run lint check
      run: npm run lint:check
    - name: Run unit tests
      run: npm run test:CI
      continue-on-error: true
    - name: Run build to check that it succeeds
      run: npm run build_aot_gzip
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [inspection_and_tests]
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: sushant-kum
